name: fl_pip
description: A picture-in-picture plugin for android and ios that can display any flutter view
version: 2.0.0
repository: https://github.com/Wayaer/fl_pip.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: fl.pip
        pluginClass: FlPiPPlugin
      ios:
        pluginClass: FlPiPPlugin
  assets:
    - assets/
